import type { Product } from "@/lib/products";

/**
 * Catálogo de equipos BLCC.
 *
 * Los datos técnicos (capacidades, dimensiones, consumos y configuraciones)
 * provienen del documento maestro y deben confirmarse con SV Solavi antes de
 * cerrar una venta. No se publican precios.
 */
export const products: Product[] = [
  // ===================================================================
  // LAVADO INDUSTRIAL
  // ===================================================================
  {
    id: "xgq",
    slug: "lavadora-extractora-xgq",
    category: "lavado-industrial",
    name: "Lavadora extractora automática",
    series: "Serie XGQ 15-30",
    summary:
      "La serie XGQ integra lavado y extracción en un solo equipo para lavanderías comerciales e industriales. Está disponible en capacidades desde 15 hasta 30 kg, ideal para operaciones medianas.",
    capacities: ["15 kg", "20 kg", "25 kg", "30 kg"],
    heatingMethods: ["Electricidad", "Vapor"],
    applications: [
      "Hoteles",
      "Hospitales y clínicas",
      "Lavanderías comerciales",
      "Centros de hospedaje",
      "Procesamiento de uniformes",
    ],
    benefits: [
      "Tambor interior fabricado en acero inoxidable SUS304.",
      "Control mediante microcomputadora.",
      "Variación de velocidad para diferentes etapas del ciclo.",
      "Sistema de suspensión y absorción de vibraciones.",
      "Puerta de gran apertura para carga, descarga e inspección.",
      "Compartimiento de detergente separado.",
      "Motor de frecuencia variable.",
      "Versiones configurables en diferentes colores.",
    ],
    imageAlt: "Lavadora extractora industrial BLCC de la serie XGQ 15-30",
    image: "/images/products/xgq.jpg",
    featured: true,
    ctaLabel: "Cotizar serie XGQ 15-30",
    relatedProductIds: ["xgq-50-150", "xsx", "hg", "mg-tl"],
    specTables: [
      {
        title: "Modelos compactos y medianos",
        columns: ["XGQ-15", "XGQ-20", "XGQ-25", "XGQ-30"],
        rows: [
          { label: "Capacidad", values: ["15 kg", "20 kg", "25 kg", "30 kg"] },
          { label: "Voltaje nominal", values: ["220/380 V", "220/380 V", "220/380 V", "220/380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Calentamiento", values: ["Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor"] },
          { label: "Tambor", values: ["730 × 400 mm", "730 × 550 mm", "800 × 500 mm", "800 × 600 mm"] },
          { label: "Velocidad de lavado", values: ["45 rpm", "45 rpm", "45 rpm", "45 rpm"] },
          { label: "Velocidad de distribución", values: ["400 rpm", "400 rpm", "400 rpm", "350 rpm"] },
          { label: "Alta extracción", values: ["800 rpm", "800 rpm", "800 rpm", "700 rpm"] },
          { label: "Potencia de motor", values: ["2.2 kW", "2.2 kW", "3 kW", "4 kW"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Entrada agua fría", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Entrada agua caliente", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Entrada de vapor", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Drenaje", values: ["Ø50 mm", "Ø50 mm", "Ø60 mm", "Ø60 mm"] },
          { label: "Peso neto", values: ["670 kg", "810 kg", "850 kg", "930 kg"] },
          { label: "Dimensiones", values: ["1220 × 1040 × 1730 mm", "1220 × 1115 × 1730 mm", "1220 × 1090 × 1730 mm", "1220 × 1280 × 1730 mm"] },
        ],
      },
    ],
  },
  {
    id: "xgq-50-150",
    slug: "lavadora-extractora-xgq-50-150",
    category: "lavado-industrial",
    name: "Lavadora extractora automática",
    series: "Serie XGQ 50-150",
    summary:
      "La serie XGQ integra lavado y extracción en un solo equipo para lavanderías industriales de mayor volumen. Está disponible en capacidades desde 50 hasta 150 kg, para plantas de procesamiento intensivo.",
    capacities: ["50 kg", "100 kg", "130 kg", "150 kg"],
    heatingMethods: ["Electricidad", "Vapor"],
    applications: [
      "Lavanderías industriales",
      "Plantas de procesamiento de uniformes",
      "Hospitales y clínicas de gran volumen",
      "Operaciones con altos volúmenes de blancos",
    ],
    benefits: [
      "Tambor interior fabricado en acero inoxidable SUS304.",
      "Control mediante microcomputadora.",
      "Variación de velocidad para diferentes etapas del ciclo.",
      "Sistema de suspensión y absorción de vibraciones.",
      "Puerta de gran apertura para carga, descarga e inspección.",
      "Compartimiento de detergente separado.",
      "Motor de frecuencia variable.",
      "Versiones configurables en diferentes colores.",
    ],
    imageAlt: "Lavadora extractora industrial BLCC de la serie XGQ 50-150",
    image: "/images/products/xgq-50-150.jpg",
    ctaLabel: "Cotizar serie XGQ 50-150",
    relatedProductIds: ["xgq", "xsx", "hg", "mg-tl"],
    specTables: [
      {
        title: "Modelos de gran capacidad",
        columns: ["XGQ-50", "XGQ-100", "XGQ-130", "XGQ-150"],
        rows: [
          { label: "Capacidad", values: ["50 kg", "100 kg", "130 kg", "150 kg"] },
          { label: "Voltaje nominal", values: ["AC 110/220/380/415/440 V", "AC 110/220/380/415/440 V", "AC 110/220/380/415/440 V", "AC 110/220/380/415/440 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Calentamiento", values: ["Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor"] },
          { label: "Tambor", values: ["1080 × 600 mm", "1250 × 840 mm", "1350 × 920 mm", "1450 × 920 mm"] },
          { label: "Velocidad de lavado", values: ["36 rpm", "36 rpm", "36 rpm", "36 rpm"] },
          { label: "Velocidad de distribución", values: ["350 rpm", "350 rpm", "350 rpm", "350 rpm"] },
          { label: "Alta extracción", values: ["700 rpm", "700 rpm", "700 rpm", "700 rpm"] },
          { label: "Potencia de motor", values: ["5.5 kW", "7.5 kW", "15 kW", "18 kW"] },
          { label: "Potencia de calentamiento", values: ["24 kW", "30 kW", "30 kW", "30 kW"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Entrada agua fría", values: ["Ø40 mm", "Ø40 mm", "Ø40 mm", "Ø60 mm"] },
          { label: "Entrada agua caliente", values: ["Ø40 mm", "Ø40 mm", "Ø40 mm", "Ø60 mm"] },
          { label: "Entrada de vapor", values: ["Ø40 mm", "Ø40 mm", "Ø40 mm", "Ø60 mm"] },
          { label: "Drenaje", values: ["Ø110 mm", "Ø140 mm", "2 × Ø110 mm", "2 × Ø110 mm"] },
          { label: "Peso neto", values: ["1910 kg", "3030 kg", "4650 kg", "6100 kg"] },
          { label: "Dimensiones", values: ["1650 × 1680 × 2050 mm", "1860 × 2160 × 2000 mm", "2000 × 2670 × 2050 mm", "2400 × 2850 × 2220 mm"] },
        ],
      },
    ],
  },
  {
    id: "xsx",
    slug: "lavadora-extractora-xsx",
    category: "lavado-industrial",
    name: "Lavadora extractora automática suspendida",
    series: "Serie XSX",
    summary:
      "La serie XSX es una lavadora extractora compacta con sistema suspendido, diseñada para reducir vibraciones y facilitar su integración en lavanderías comerciales, hoteles y operaciones con capacidades de 15 a 25 kg.",
    capacities: ["15 kg", "20 kg", "25 kg"],
    heatingMethods: ["Electricidad", "Vapor"],
    benefits: [
      "Diseño suspendido para mejorar el balance operativo.",
      "Sistema de resortes y absorción de impactos.",
      "Amortiguadores hidráulicos para estabilización.",
      "Velocidad máxima cercana a 900 rpm según modelo.",
      "Tambor y panel exterior en acero inoxidable 304.",
      "Iluminación interior azul.",
      "Control electrónico programable.",
    ],
    imageAlt: "Lavadora extractora suspendida BLCC de la serie XSX",
    image: "/images/products/xsx.jpg",
    ctaLabel: "Solicitar cotización de XSX",
    relatedProductIds: ["xgq", "hg"],
    specTables: [
      {
        columns: ["XSX-15", "XSX-20", "XSX-25"],
        rows: [
          { label: "Capacidad", values: ["15 kg", "20 kg", "25 kg"] },
          { label: "Voltaje nominal", values: ["220/380 V", "220/380 V", "220/380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Calentamiento", values: ["Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor"] },
          { label: "Velocidad de lavado", values: ["45 rpm", "45 rpm", "45 rpm"] },
          { label: "Velocidad de distribución", values: ["400 rpm", "400 rpm", "400 rpm"] },
          { label: "Alta extracción", values: ["900 rpm", "900 rpm", "900 rpm"] },
          { label: "Potencia de motor", values: ["2.2 kW", "2.2 kW", "3 kW"] },
          { label: "Potencia de calentamiento", values: ["12 kW a 220/380 V", "12 kW a 220/380 V", "14 kW a 220/380 V"] },
          { label: "Consumo de agua", values: ["180 L", "220 L", "280 L"] },
          { label: "Consumo de gas indicado", values: ["≤20 kg", "≤20 kg", "≤20 kg"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Entrada agua fría", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Entrada agua caliente", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Entrada de vapor", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Drenaje", values: ["Ø75 mm", "Ø75 mm", "Ø75 mm"] },
          { label: "Peso neto", values: ["520 kg", "530 kg", "560 kg"] },
          { label: "Dimensiones", values: ["980 × 1200 × 1400 mm", "980 × 1250 × 1400 mm", "980 × 1250 × 1400 mm"] },
        ],
      },
    ],
  },
  {
    id: "bw",
    slug: "lavadora-barrera-sanitaria-bw",
    category: "lavado-industrial",
    name: "Lavadora de barrera sanitaria",
    series: "Serie BW",
    summary:
      "Lavadora de barrera sanitaria con acceso por dos lados, diseñada para separar físicamente el área de carga sucia y el área de descarga limpia. Es una solución especialmente relevante para hospitales, clínicas, laboratorios y operaciones con protocolos de higiene estrictos.",
    capacities: ["20 kg", "30 kg", "50 kg", "100 kg"],
    heatingMethods: ["Electricidad", "Vapor", "Gas"],
    benefits: [
      "Cámara interna y estructura exterior en acero inoxidable 304.",
      "Diseño de doble acceso.",
      "Separación entre zona contaminada y zona limpia.",
      "Sistema automático de bloqueo de puertas.",
      "Control mediante interruptores de proximidad.",
      "Diseño de alta resistencia.",
      "Absorción de vibraciones.",
      "Pantalla táctil con interfaz de operación.",
      "Monitoreo del proceso.",
    ],
    imageAlt: "Lavadora de barrera sanitaria BLCC de la serie BW",
    featured: true,
    ctaLabel: "Evaluar una solución de barrera sanitaria",
    relatedProductIds: ["hg", "xgq"],
    specTables: [
      {
        columns: ["BW-20", "BW-30", "BW-50", "BW-100"],
        rows: [
          { label: "Capacidad", values: ["20 kg", "30 kg", "50 kg", "100 kg"] },
          { label: "Alimentación", values: ["380 V / 3 fases / 50 Hz", "380 V / 3 fases / 50 Hz", "380 V / 3 fases / 50 Hz", "380 V / 3 fases / 50 Hz"] },
          { label: "Tambor interno", values: ["730 × 490 mm", "900 × 500 mm", "970 × 720 mm", "1200 × 890 mm"] },
          { label: "Potencia de motor", values: ["2.2 kW", "4 kW", "5.5 kW", "11 kW"] },
          { label: "Velocidad de lavado", values: ["35 rpm", "35 rpm", "35 rpm", "32 rpm"] },
          { label: "Rotación uniforme", values: ["70 rpm", "70 rpm", "70 rpm", "65 rpm"] },
          { label: "Distribución", values: ["440 rpm", "400 rpm", "370 rpm", "350 rpm"] },
          { label: "Alta extracción", values: ["920 rpm", "800 rpm", "750 rpm", "750 rpm"] },
          { label: "Tubería de vapor", values: ["DN20", "DN20", "DN20", "DN25"] },
          { label: "Entrada", values: ["DN40", "DN40", "DN40", "DN50"] },
          { label: "Drenaje", values: ["Ø89 mm", "Ø89 mm", "Ø89 mm", "Ø140 mm"] },
          { label: "Presión de entrada", values: ["0.2–0.3 MPa", "0.2–0.3 MPa", "0.2–0.3 MPa", "0.2–0.3 MPa"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Calentamiento eléctrico", values: ["18 kW", "24 kW", "36 kW", "48 kW"] },
          { label: "Consumo de agua indicado", values: ["300 kg", "450 kg", "700 kg", "1650 kg"] },
          { label: "Consumo de gas indicado", values: ["15 kg", "25 kg", "45 kg", "50 kg"] },
          { label: "Peso neto", values: ["800 kg", "1140 kg", "2000 kg", "3000 kg"] },
          { label: "Dimensiones", values: ["1250 × 1360 × 1690 mm", "1400 × 1370 × 1800 mm", "1500 × 1640 × 1880 mm", "1720 × 1810 × 2150 mm"] },
        ],
      },
    ],
  },
  {
    id: "xgb",
    slug: "lavadora-horizontal-xgb",
    category: "lavado-industrial",
    name: "Lavadora horizontal",
    series: "Serie XGB",
    summary:
      "Lavadora horizontal para procesos de lavado por lotes. Es una alternativa sencilla para operaciones que utilizan una centrífuga independiente para la extracción posterior.",
    capacities: ["30 kg", "50 kg", "70 kg", "100 kg"],
    benefits: [
      "Tambor de acero inoxidable.",
      "Resistencia a corrosión.",
      "Control de tiempo y temperatura mediante microcomputadora.",
      "Estructura sencilla.",
      "Operación y mantenimiento accesibles.",
      "Bajo ruido.",
      "Sellos resistentes al desgaste.",
    ],
    imageAlt: "Lavadora horizontal BLCC de la serie XGB",
    ctaLabel: "Cotizar lavadora horizontal XGB",
    relatedProductIds: ["mg-tl", "xgq"],
    specTables: [
      {
        columns: ["XGB-30", "XGB-50", "XGB-70", "XGB-100"],
        rows: [
          { label: "Capacidad", values: ["30 kg", "50 kg", "70 kg", "100 kg"] },
          { label: "Alimentación", values: ["380 V", "380 V", "380 V", "380 V"] },
          { label: "Velocidad de lavado", values: ["35 rpm", "35 rpm", "35 rpm", "32 rpm"] },
          { label: "Ciclo de lavado", values: ["30–40 min", "30–40 min", "30–40 min", "30–40 min"] },
          { label: "Potencia de motor", values: ["1.1 kW", "2.2 kW", "3 kW", "4 kW"] },
          { label: "Peso neto", values: ["324 kg", "450 kg", "550 kg", "950 kg"] },
          { label: "Dimensiones", values: ["1250 × 1400 × 1200 mm", "1400 × 1500 × 1400 mm", "1500 × 1880 × 1490 mm", "1600 × 2250 × 1750 mm"] },
        ],
      },
    ],
  },

  // ===================================================================
  // SECADO INDUSTRIAL
  // ===================================================================
  {
    id: "hg",
    slug: "secadora-industrial-hg",
    category: "secado-industrial",
    name: "Secadora automática industrial",
    series: "Serie HG",
    summary:
      "La serie HG ofrece secado profesional para lavanderías comerciales e industriales. Está disponible en capacidades de 15 a 150 kg y admite distintas fuentes de calentamiento según configuración.",
    capacities: ["15 kg", "20 kg", "25 kg", "35 kg", "50 kg", "70 kg", "100 kg", "150 kg"],
    heatingMethods: ["Electricidad", "Vapor", "Gas LP", "Gas", "Gas natural"],
    applications: [
      "Hoteles",
      "Hospitales",
      "Lavanderías industriales",
      "Procesamiento de uniformes",
      "Lavanderías comerciales",
      "Centros deportivos y residencias",
    ],
    benefits: [
      "Tambor de acero inoxidable SUS304.",
      "Control por microcomputadora.",
      "Programación de tiempo, temperatura y enfriamiento.",
      "Operación suave y de bajo ruido.",
      "Puerta de gran apertura.",
      "Colector de pelusa extraíble.",
      "Flujo de aire de alta densidad.",
      "Colores personalizables.",
      "Calentamiento eléctrico, vapor, gas licuado, gas o gas natural, según modelo.",
    ],
    imageAlt: "Secadora industrial BLCC de la serie HG",
    image: "/images/products/hg.jpg",
    featured: true,
    ctaLabel: "Cotizar secadora HG",
    relatedProductIds: ["xgq", "hgq", "yp"],
    specTables: [
      {
        title: "Modelos de 15 a 35 kg",
        columns: ["HG-15", "HG-20", "HG-25", "HG-35"],
        rows: [
          { label: "Capacidad", values: ["15 kg", "20 kg", "25 kg", "35 kg"] },
          { label: "Voltaje nominal", values: ["220/380 V", "220/380 V", "220/380 V", "380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Calentamiento", values: ["Electricidad / vapor / gas LP / gas / gas natural", "Igual", "Igual", "Igual"] },
          { label: "Tambor", values: ["750 × 475 mm", "750 × 575 mm", "750 × 675 mm", "970 × 900 mm"] },
          { label: "Velocidad de secado", values: ["36 rpm", "36 rpm", "36 rpm", "36 rpm"] },
          { label: "Potencia de motor", values: ["0.12 kW", "0.12 kW", "0.75 kW", "0.75 kW"] },
          { label: "Ventilador", values: ["0.55 kW", "0.55 kW", "0.55 kW", "0.75 kW"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Ducto de salida", values: ["110 mm", "110 mm", "110 mm", "160 mm"] },
          { label: "Peso neto", values: ["240 kg", "240 kg", "240 kg", "480 kg"] },
          { label: "Dimensiones", values: ["900 × 1010 × 1700 mm", "900 × 1060 × 1700 mm", "900 × 1160 × 1700 mm", "1060 × 1500 × 1900 mm"] },
        ],
      },
      {
        title: "Modelos de 50 a 150 kg",
        columns: ["HG-50", "HG-70", "HG-100", "HG-150"],
        rows: [
          { label: "Capacidad", values: ["50 kg", "70 kg", "100 kg", "150 kg"] },
          { label: "Voltaje nominal", values: ["380 V", "380 V", "380 V", "380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Calentamiento", values: ["Electricidad / vapor / gas LP / gas / gas natural", "Igual", "Igual", "Igual"] },
          { label: "Tambor", values: ["1140 × 970 mm", "1140 × 1070 mm", "1460 × 1220 mm", "1810 × 1260 mm"] },
          { label: "Velocidad de secado", values: ["36 rpm", "36 rpm", "36 rpm", "36 rpm"] },
          { label: "Potencia de motor", values: ["1.1 kW", "1.1 kW", "2.2 kW", "4 kW"] },
          { label: "Ventilador", values: ["1.5 kW", "1.5 kW", "2 × 1.5 kW", "2 × 1.5 kW"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Ducto de salida", values: ["160 mm", "160 mm", "260 mm", "260 mm"] },
          { label: "Peso neto", values: ["640 kg", "640 kg", "1200 kg", "2200 kg"] },
          { label: "Dimensiones", values: ["1305 × 1650 × 2130 mm", "1305 × 1750 × 2130 mm", "1700 × 2050 × 2700 mm", "2050 × 2330 × 3000 mm"] },
        ],
      },
    ],
  },

  // ===================================================================
  // AUTOSERVICIO
  // ===================================================================
  {
    id: "swq",
    slug: "lavadora-autoservicio-swq",
    category: "autoservicio",
    name: "Lavadora de autoservicio",
    series: "Serie SWQ",
    summary:
      "La serie SWQ está diseñada para lavanderías de autoservicio y operaciones que requieren cobro por ciclo. Según configuración, puede integrar monedas, tarjeta u otros sistemas compatibles.",
    capacities: ["12 kg", "15 kg", "20 kg", "25 kg"],
    heatingMethods: ["Electricidad", "Vapor"],
    benefits: [
      "Sistema de control cableado.",
      "Posibilidad de configurar monedas y tarjeta.",
      "Contenedor de detergente.",
      "Tambor interior de acero inoxidable SUS304.",
      "Control por microcomputadora.",
      "Seguro de puerta con interbloqueo.",
      "Alternativas de color.",
      "Adecuada para hoteles, residencias, lavanderías y escuelas.",
    ],
    imageAlt: "Lavadora de autoservicio BLCC de la serie SWQ",
    image: "/images/products/swq.jpg",
    featured: true,
    ctaLabel: "Diseñar mi lavandería de autoservicio",
    relatedProductIds: ["hgq", "xth", "shg"],
    specTables: [
      {
        columns: ["SWQ-12", "SWQ-15", "SWQ-20", "SWQ-25"],
        rows: [
          { label: "Capacidad", values: ["12 kg", "15 kg", "20 kg", "25 kg"] },
          { label: "Voltaje", values: ["AC 110/220/380/415/440 V", "Igual", "Igual", "Igual"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Tambor", values: ["670 × 364 mm", "670 × 450 mm", "670 × 524 mm", "670 × 600 mm"] },
          { label: "Ruido indicado", values: ["≤70 dB", "≤70 dB", "≤70 dB", "≤70 dB"] },
          { label: "Calentamiento", values: ["Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor", "Electricidad / vapor"] },
          { label: "Velocidad de lavado", values: ["45 rpm", "45 rpm", "45 rpm", "45 rpm"] },
          { label: "Distribución", values: ["350 rpm", "350 rpm", "350 rpm", "350 rpm"] },
          { label: "Alta extracción", values: ["700 rpm", "700 rpm", "700 rpm", "700 rpm"] },
          { label: "Potencia de motor", values: ["2.2 kW", "2.2 kW", "2.2 kW", "2.2 kW"] },
          { label: "Potencia de calentamiento", values: ["8 kW", "8 kW", "8 kW", "8 kW"] },
          { label: "Consumo de agua", values: ["115 L", "130 L", "165 L", "200 L"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Entradas agua/vapor", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Drenaje", values: ["Ø75 mm", "Ø75 mm", "Ø75 mm", "Ø75 mm"] },
          { label: "Peso neto", values: ["360 kg", "380 kg", "380 kg", "410 kg"] },
          { label: "Dimensiones", values: ["900 × 1050 × 1330 mm", "900 × 1050 × 1330 mm", "900 × 1110 × 1330 mm", "900 × 1160 × 1330 mm"] },
        ],
      },
    ],
  },
  {
    id: "hgq",
    slug: "secadora-autoservicio-hgq",
    category: "autoservicio",
    name: "Secadora de autoservicio",
    series: "Serie HGQ",
    summary:
      "Secadora comercial para lavanderías de autoservicio, con panel de control y sistema de cobro configurable. Permite seleccionar diferentes métodos de calentamiento de acuerdo con la instalación.",
    capacities: ["15 kg", "20 kg", "25 kg"],
    heatingMethods: ["Electricidad", "Vapor", "Gas LP", "Gas", "Gas natural"],
    benefits: [
      "Tambor de acero inoxidable SUS304.",
      "Control programable de tiempo, temperatura y enfriamiento.",
      "Operación de bajo ruido.",
      "Puerta amplia.",
      "Filtro colector de pelusa.",
      "Flujo de aire de alta densidad.",
      "Colores personalizables.",
    ],
    imageAlt: "Secadora de autoservicio BLCC de la serie HGQ",
    image: "/images/products/hgq.jpg",
    ctaLabel: "Cotizar secadora HGQ",
    relatedProductIds: ["swq", "shg", "xth"],
    specTables: [
      {
        columns: ["HGQ-15", "HGQ-20", "HGQ-25"],
        rows: [
          { label: "Capacidad", values: ["15 kg", "20 kg", "25 kg"] },
          { label: "Voltaje", values: ["220/380 V", "220/380 V", "220/380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Tambor", values: ["750 × 475 mm", "750 × 575 mm", "750 × 675 mm"] },
          { label: "Velocidad de secado", values: ["36 rpm", "36 rpm", "36 rpm"] },
          { label: "Calentamiento", values: ["Electricidad / vapor / gas LP / gas / gas natural", "Igual", "Igual"] },
          { label: "Potencia de motor", values: ["0.12 kW", "0.12 kW", "0.75 kW"] },
          { label: "Ventilador", values: ["0.55 kW", "0.55 kW", "0.55 kW"] },
          { label: "Potencia de secado", values: ["6 kW", "8 kW", "10 kW"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Ducto de salida", values: ["110 mm", "110 mm", "110 mm"] },
          { label: "Peso neto", values: ["240 kg", "240 kg", "240 kg"] },
          { label: "Dimensiones", values: ["900 × 1010 × 1700 mm", "900 × 1100 × 1800 mm", "900 × 1160 × 1700 mm"] },
        ],
      },
    ],
  },
  {
    id: "shg",
    slug: "secadora-doble-apilada-shg",
    category: "autoservicio",
    name: "Secadora doble apilada con monedas o QR",
    series: "Serie SHG",
    summary:
      "La serie SHG integra dos secadoras en una misma huella de piso para maximizar la capacidad de atención en lavanderías de autoservicio. Puede configurarse con sistemas de cobro por moneda, tarjeta o QR según el proyecto.",
    capacities: ["15 kg", "20 kg", "25 kg"],
    heatingMethods: ["Electricidad", "Gas LP", "Gas", "Gas natural"],
    benefits: [
      "Dos módulos de secado independientes en formato vertical.",
      "Reducción del espacio ocupado.",
      "Tambor de acero inoxidable SUS304.",
      "Operación configurable mediante sistemas de cobro.",
      "Control por microcomputadora.",
      "Sistema de circulación térmica.",
      "Opciones de color.",
      "Alternativas de calentamiento eléctrico o gas, según configuración.",
    ],
    imageAlt: "Secadora doble apilada BLCC de la serie SHG",
    image: "/images/products/shg.jpg",
    technicalNotice:
      "Confirmar con fábrica si la capacidad indicada corresponde a cada tambor o a la capacidad comercial total del equipo.",
    ctaLabel: "Cotizar secadora doble SHG",
    relatedProductIds: ["hgq", "xth", "swq"],
    specTables: [
      {
        columns: ["SHG-15", "SHG-20", "SHG-25"],
        rows: [
          { label: "Capacidad indicada", values: ["15 kg", "20 kg", "25 kg"] },
          { label: "Voltaje", values: ["AC 220/380 V", "AC 220/380 V", "AC 220/380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Tambor", values: ["760 × 695 mm", "760 × 695 mm", "760 × 855 mm"] },
          { label: "Calentamiento", values: ["Electricidad / gas LP / gas / gas natural", "Igual", "Igual"] },
          { label: "Velocidad de secado", values: ["40 rpm", "40 rpm", "36 rpm"] },
          { label: "Potencia de motor", values: ["0.37 kW", "0.37 kW", "0.37 kW"] },
          { label: "Ventilador", values: ["0.55 kW", "0.55 kW", "0.55 kW"] },
          { label: "Potencia de secado", values: ["9 kW", "9 kW", "9 kW"] },
          { label: "Consumo de aire indicado", values: ["20–30 kg", "30–35 kg", "30–35 kg"] },
          { label: "Presión de vapor indicada", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Ducto de salida", values: ["Ø160 mm", "Ø160 mm", "Ø160 mm"] },
          { label: "Peso neto", values: ["290 kg", "290 kg", "420 kg"] },
          { label: "Dimensiones", values: ["800 × 1160 × 1920 mm", "800 × 1160 × 1920 mm", "800 × 1330 × 1920 mm"] },
        ],
      },
    ],
  },
  {
    id: "xth",
    slug: "torre-lavadora-secadora-xth",
    category: "autoservicio",
    name: "Torre lavadora-secadora con monedas o QR",
    series: "Serie XTH",
    summary:
      "La serie XTH combina una lavadora y una secadora en una sola columna. Está orientada a lavanderías de autoservicio que buscan aumentar el número de equipos disponibles sin ampliar su superficie.",
    capacities: ["12 kg", "15 kg", "20 kg", "25 kg"],
    heatingMethods: ["Electricidad", "Vapor", "Gas LP", "Gas", "Gas natural"],
    benefits: [
      "Lavado y secado en una misma huella de piso.",
      "Tambor interior de acero inoxidable SUS304.",
      "Procesos controlados por microcomputadora.",
      "Compatibilidad configurable con monedas, tarjeta, código o QR.",
      "Configuración compacta.",
      "Diferentes métodos de calentamiento.",
      "Opciones de color.",
    ],
    imageAlt: "Torre lavadora-secadora BLCC de la serie XTH",
    image: "/images/products/xth.jpg",
    featured: true,
    ctaLabel: "Diseñar una lavandería con torres XTH",
    relatedProductIds: ["swq", "hgq", "shg"],
    specTables: [
      {
        columns: ["XTH-12", "XTH-15", "XTH-20", "XTH-25"],
        rows: [
          { label: "Capacidad", values: ["12 kg", "15 kg", "20 kg", "25 kg"] },
          { label: "Voltaje", values: ["AC 110/220/380/415/440 V", "Igual", "Igual", "Igual"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Tambor de lavado", values: ["670 × 364 mm", "670 × 450 mm", "670 × 524 mm", "670 × 575 mm"] },
          { label: "Tambor de secado", values: ["760 × 696 mm", "760 × 696 mm", "760 × 696 mm", "760 × 855 mm"] },
          { label: "Velocidad de lavado", values: ["45 rpm", "45 rpm", "45 rpm", "45 rpm"] },
          { label: "Velocidad de secado", values: ["36 rpm", "36 rpm", "36 rpm", "36 rpm"] },
          { label: "Motor de lavado", values: ["2.2 kW", "2.2 kW", "2.2 kW", "2.2 kW"] },
          { label: "Motor de secado", values: ["0.37 kW", "0.37 kW", "0.37 kW", "0.37 kW"] },
          { label: "Ventilador de secado", values: ["0.55 kW", "0.55 kW", "0.55 kW", "0.55 kW"] },
          { label: "Calentamiento de lavado", values: ["8 kW", "8 kW", "8 kW", "8 kW"] },
          { label: "Método de calentamiento", values: ["Electricidad / vapor / gas LP / gas / gas natural", "Igual", "Igual", "Igual"] },
          { label: "Potencia de secado", values: ["9 kW", "9 kW", "9 kW", "9 kW"] },
          { label: "Consumo de agua", values: ["115 L", "130 L", "165 L", "200 L"] },
          { label: "Consumo de gas indicado", values: ["≤16 kg", "≤18 kg", "≤20 kg", "≤25 kg"] },
          { label: "Consumo de aire indicado", values: ["15–18 kg", "20–30 kg", "30–35 kg", "36–45 kg"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa", "0.4–0.6 MPa"] },
          { label: "Entradas agua/vapor", values: ["Ø20 mm", "Ø20 mm", "Ø20 mm", "Ø20 mm"] },
          { label: "Drenaje", values: ["Ø75 mm", "Ø75 mm", "Ø75 mm", "Ø75 mm"] },
          { label: "Peso neto", values: ["520 kg", "520 kg", "530 kg", "550 kg"] },
          { label: "Dimensiones", values: ["900 × 1180 × 2080 mm", "900 × 1180 × 2080 mm", "900 × 1180 × 2080 mm", "900 × 1330 × 2080 mm"] },
        ],
      },
    ],
  },

  // ===================================================================
  // LAVADO EN SECO
  // ===================================================================
  {
    id: "swh",
    slug: "lavado-seco-hidrocarburo-swh",
    category: "lavado-en-seco",
    name: "Máquina de lavado en seco con hidrocarburo",
    series: "Serie SWH",
    summary:
      "La serie SWH utiliza hidrocarburo para el cuidado profesional de prendas. Su configuración está orientada a tintorerías que requieren ciclos automáticos o manuales y recuperación del solvente para reutilización.",
    capacities: ["10 kg", "12 kg", "15 kg"],
    benefits: [
      "Tambor interior de acero inoxidable SUS304.",
      "Operación automática o manual.",
      "Diferentes modos de lavado.",
      "Sistema suspendido de absorción de vibraciones.",
      "Puerta y visor amplios.",
      "Tanques dobles de líquido.",
      "Sistema de filtración para recuperación y reutilización del solvente.",
      "Diferentes colores disponibles.",
    ],
    imageAlt: "Máquina de lavado en seco con hidrocarburo BLCC de la serie SWH",
    image: "/images/products/swh.jpg",
    featured: true,
    ctaLabel: "Cotizar equipo SWH",
    relatedProductIds: ["gxzq", "sws", "rxj-1"],
    specTables: [
      {
        columns: ["SWH-10", "SWH-12", "SWH-15"],
        rows: [
          { label: "Capacidad", values: ["10 kg", "12 kg", "15 kg"] },
          { label: "Voltaje", values: ["220/380 V", "220/380 V", "220/380 V"] },
          { label: "Frecuencia", values: ["50/60 Hz", "50/60 Hz", "50/60 Hz"] },
          { label: "Velocidad de lavado", values: ["40 rpm", "40 rpm", "40 rpm"] },
          { label: "Potencia de motor", values: ["1.5 kW", "1.5 kW", "1.5 kW"] },
          { label: "Material exterior", values: ["Acero al carbón con recubrimiento plástico", "Igual", "Igual"] },
          { label: "Tambor", values: ["Acero inoxidable 304", "Acero inoxidable 304", "Acero inoxidable 304"] },
          { label: "Peso neto", values: ["630 kg", "630 kg", "630 kg"] },
          { label: "Dimensiones", values: ["1580 × 1040 × 1730 mm", "1580 × 1040 × 1730 mm", "1580 × 1040 × 1730 mm"] },
        ],
      },
    ],
  },
  {
    id: "gxzq",
    slug: "lavado-seco-percloroetileno-gxzq",
    category: "lavado-en-seco",
    name: "Máquina cerrada de lavado en seco con percloroetileno",
    series: "Serie GXZQ",
    summary:
      "La serie GXZQ es una solución cerrada para tintorería profesional con percloroetileno. Integra lavado, filtración y recuperación de solvente en un sistema compacto.",
    capacities: ["10 kg", "12 kg", "15 kg"],
    benefits: [
      "Tambor de acero inoxidable SUS304.",
      "Control por microcomputadora con pantalla amplia.",
      "Diferentes programas de lavado.",
      "Sistema de recuperación por refrigeración.",
      "Recuperación de solvente comunicada por el fabricante superior al 99%.",
      "Puerta de gran apertura.",
      "Sistema de adsorción con carbón activado.",
      "Tres tanques de solvente.",
      "Sistema de autolimpieza y doble filtración.",
    ],
    imageAlt: "Máquina cerrada de lavado en seco con percloroetileno BLCC de la serie GXZQ",
    technicalNotice:
      "La instalación, operación, ventilación y manejo de solventes deben cumplir la normativa local aplicable. SV Solavi debe validar los requisitos regulatorios y de seguridad antes de ofrecer este equipo.",
    ctaLabel: "Hablar con un especialista en tintorería",
    relatedProductIds: ["swh", "sws", "ct"],
    specTables: [
      {
        columns: ["GXZQ-10", "GXZQ-12", "GXZQ-15"],
        rows: [
          { label: "Capacidad", values: ["10 kg", "12 kg", "15 kg"] },
          { label: "Voltaje", values: ["220/380 V", "220/380 V", "220/380 V"] },
          { label: "Volumen de tambor", values: ["200 L", "320 L", "450 L"] },
          { label: "Ruido indicado", values: ["≤75 dB", "≤75 dB", "≤75 dB"] },
          { label: "Acabado exterior", values: ["Pintura horneada", "Pintura horneada", "Pintura horneada"] },
          { label: "Tambor", values: ["Acero inoxidable 304", "Acero inoxidable 304", "Acero inoxidable 304"] },
          { label: "Peso neto", values: ["560 kg", "580 kg", "600 kg"] },
          { label: "Dimensiones", values: ["1600 × 1300 × 2050 mm", "1600 × 1300 × 2050 mm", "1600 × 1300 × 2050 mm"] },
        ],
      },
    ],
  },

  // ===================================================================
  // PLANCHADO Y DOBLADO
  // ===================================================================
  {
    id: "yp",
    slug: "calandra-industrial-yp",
    category: "planchado-y-doblado",
    name: "Calandra industrial para textiles planos",
    series: "Serie YP",
    summary:
      "Calandra industrial para planchado y secado continuo de sábanas, mantelería y textiles planos. Las configuraciones con mayor número de rodillos incrementan la velocidad y capacidad de procesamiento.",
    capacities: ["Uno a cuatro rodillos"],
    heatingMethods: ["Electricidad", "Gas"],
    benefits: [
      "Construcción en acero inoxidable en componentes principales.",
      "Calentamiento rápido.",
      "Diferentes configuraciones de rodillos.",
      "Tecnología orientada a alta velocidad y eficiencia.",
      "Extracción de humedad mediante presión y temperatura.",
      "Ajuste continuo de velocidad.",
      "Sistema de bandas para estabilizar el transporte del textil.",
      "Control de temperatura para operación segura.",
    ],
    imageAlt: "Calandra industrial BLCC de la serie YP",
    featured: true,
    ctaLabel: "Cotizar una línea de planchado",
    relatedProductIds: ["zd3300-v", "ings-3300", "hg"],
    specTables: [
      {
        columns: ["YPI-3000", "YPII-3000", "YPIII-3000", "YPIV-3000"],
        rows: [
          { label: "Configuración", values: ["Un rodillo", "Dos rodillos", "Tres rodillos", "Cuatro rodillos"] },
          { label: "Diámetro de rodillo", values: ["600–800 mm", "600–800 mm", "600–800 mm", "600–800 mm"] },
          { label: "Calentamiento", values: ["Eléctrico / gas", "Eléctrico / gas", "Eléctrico / gas", "Eléctrico / gas"] },
          { label: "Ancho máximo", values: ["3000 mm", "3000 mm", "3000 mm", "3000 mm"] },
          { label: "Velocidad de planchado", values: ["0–25 m/min", "0–40 m/min", "0–60 m/min", "0–80 m/min"] },
          { label: "Capacidad con vapor indicada", values: ["100 kg/h", "200 kg/h", "300 kg/h", "400 kg/h"] },
          { label: "Presión de vapor", values: ["0.3–0.5 MPa", "0.3–0.5 MPa", "0.3–0.5 MPa", "0.3–0.5 MPa"] },
          { label: "Potencia eléctrica de calentamiento", values: ["36 kW", "72 kW", "108 kW", "144 kW"] },
          { label: "Potencia de motor", values: ["1.1 kW", "2.2 kW", "3 kW", "3 kW"] },
          { label: "Consumo de gas indicado", values: ["5 m³/h", "10 m³/h", "15 m³/h", "20 m³/h"] },
          { label: "Material de rodillo", values: ["304", "304", "304", "304"] },
          { label: "Voltaje", values: ["380 V", "380 V", "380 V", "380 V"] },
          { label: "Peso neto", values: ["1400 kg", "2800 kg", "3000 kg", "4000 kg"] },
          { label: "Dimensiones", values: ["4150 × 1420 × 1500 mm", "4150 × 2370 × 1500 mm", "4200 × 3300 × 1500 mm", "4200 × 4300 × 1500 mm"] },
        ],
      },
    ],
  },
  {
    id: "zd3300-v",
    slug: "dobladora-zd3300-v",
    category: "planchado-y-doblado",
    name: "Máquina dobladora ZD3300-V",
    summary:
      "Máquina automática para doblado de textiles planos, diseñada para integrarse con una línea de planchado y reducir trabajo manual.",
    capacities: ["Ancho máximo 3300 mm"],
    benefits: [
      "Sistema de diagnóstico, protección y alarmas.",
      "Doblado horizontal y vertical.",
      "Configuración de cuatro canales.",
      "Posicionamiento preciso del transporte.",
      "Medición y cálculo de longitud.",
      "Integración directa con calandra.",
      "Pantalla de control.",
      "Hasta 30 programas de doblado.",
      "Sistema de velocidad variable.",
      "Función antiestática.",
    ],
    imageAlt: "Máquina dobladora BLCC ZD3300-V",
    ctaLabel: "Cotizar dobladora ZD3300-V",
    relatedProductIds: ["yp", "ings-3300"],
    specTables: [
      {
        columns: ["ZD3300-V"],
        rows: [
          { label: "Ancho máximo de doblado", values: ["3300 mm"] },
          { label: "Capas máximas por proceso", values: ["5/32"] },
          { label: "Velocidad máxima", values: ["50 m/min"] },
          { label: "Voltaje", values: ["380 V"] },
          { label: "Potencia de motor", values: ["1.3 kW"] },
          { label: "Diámetro de entrada", values: ['G 1/2"'] },
          { label: "Peso neto", values: ["1650 kg"] },
          { label: "Dimensiones", values: ["1760 × 2800 × 4116 mm"] },
        ],
      },
    ],
  },
  {
    id: "ings-3300",
    slug: "alimentadora-ings-3300",
    category: "planchado-y-doblado",
    name: "Alimentadora de textiles INGS-3300",
    summary:
      "Alimentadora para introducir sábanas y textiles planos de forma estable en una línea de planchado, mejorando la seguridad y reduciendo la necesidad de alimentación manual.",
    capacities: ["Ancho de alimentación 3300 mm"],
    benefits: [
      "Alimentación segura hacia la calandra.",
      "Estructura compacta.",
      "Alta eficiencia.",
      "Ventilador centrífugo de alto flujo.",
      "Transporte estable del textil.",
      "Regulación continua de velocidad.",
      "Sincronización con el equipo de planchado.",
      "Botón de paro de emergencia.",
    ],
    imageAlt: "Alimentadora de textiles BLCC INGS-3300",
    ctaLabel: "Cotizar alimentadora INGS-3300",
    relatedProductIds: ["yp", "zd3300-v"],
    specTables: [
      {
        columns: ["INGS-3300"],
        rows: [
          { label: "Ancho de alimentación", values: ["3300 mm"] },
          { label: "Velocidad de alimentación", values: ["52 m/min"] },
          { label: "Voltaje", values: ["380 V"] },
          { label: "Frecuencia", values: ["50 Hz"] },
          { label: "Velocidad indicada", values: ["4.6 rpm"] },
          { label: "Peso neto", values: ["900 kg"] },
          { label: "Dimensiones", values: ["3450 × 1180 × 1310 mm"] },
        ],
      },
    ],
  },

  // ===================================================================
  // EQUIPOS COMPLEMENTARIOS Y ACABADO
  // ===================================================================
  {
    id: "mg-tl",
    slug: "centrifuga-mg-tl",
    category: "equipos-complementarios",
    name: "Centrífuga de tres patas",
    series: "Serie MG-TL",
    summary:
      "Centrífuga independiente para extracción mecánica de agua después del lavado. Su estructura de tres patas busca reducir vibraciones y facilitar una operación estable.",
    capacities: ["25 kg", "35 kg", "50 kg", "70 kg", "100 kg"],
    benefits: [
      "Suspensión de tres patas.",
      "Reducción de vibración.",
      "Cubierta y carcasa de acero inoxidable.",
      "Eje principal tratado térmicamente.",
      "Transmisión por banda.",
      "Arranque suave.",
      "Frenado rápido.",
    ],
    imageAlt: "Centrífuga de tres patas BLCC de la serie MG-TL",
    ctaLabel: "Cotizar centrífuga",
    relatedProductIds: ["xgb", "xgq"],
    specTables: [
      {
        columns: ["MG-TL25", "MG-TL35", "MG-TL50", "MG-TL70", "MG-TL100"],
        rows: [
          { label: "Capacidad", values: ["25 kg", "35 kg", "50 kg", "70 kg", "100 kg"] },
          { label: "Velocidad de extracción", values: ["850 rpm", "830 rpm", "786 rpm", "780 rpm", "780 rpm"] },
          { label: "Voltaje", values: ["380 V", "380 V", "380 V", "380 V", "380 V"] },
          { label: "Tambor", values: ["570 × 310 mm", "640 × 350 mm", "850 × 370 mm", "950 × 400 mm", "1000 × 400 mm"] },
          { label: "Potencia", values: ["1.1 kW", "3 kW", "4 kW", "5.5 kW", "7.5 kW"] },
          { label: "Peso neto", values: ["238 kg", "342 kg", "512 kg", "758 kg", "878 kg"] },
          { label: "Dimensiones", values: ["900 × 900 × 680 mm", "1100 × 1100 × 750 mm", "1250 × 1250 × 880 mm", "1500 × 1500 × 880 mm", "1600 × 1600 × 900 mm"] },
        ],
      },
    ],
  },
  {
    id: "ytt-1475",
    slug: "mesa-planchado-ytt-1475",
    category: "equipos-complementarios",
    name: "Mesa de planchado YTT-1475",
    summary:
      "Mesa profesional para planchado de algodón, lana, lino, fibras sintéticas y otras prendas. Incorpora succión para ayudar a fijar y enfriar el tejido durante el acabado.",
    benefits: [
      "Superficie de planchado con succión.",
      "Cambio mediante pedal entre mesa y brazo.",
      "Sistema de succión de alta potencia.",
      "Operación de bajo ruido.",
      "Configuración compacta.",
    ],
    imageAlt: "Mesa de planchado BLCC YTT-1475",
    ctaLabel: "Cotizar mesa de planchado YTT-1475",
    relatedProductIds: ["hxgt-1", "jtj-1", "ldr3-04r"],
    specTables: [
      {
        columns: ["YTT-1475"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Mesa", values: ["1400 × 800 mm"] },
          { label: "Potencia", values: ["0.37 kW"] },
          { label: "Dimensiones", values: ["1400 × 800 × 1050 mm"] },
          { label: "Peso neto", values: ["25 kg"] },
        ],
      },
    ],
  },
  {
    id: "ldr3-04r",
    slug: "generador-vapor-ldr3-04r",
    category: "equipos-complementarios",
    name: "Generador de vapor LDR3-0.4R",
    summary: "Generador compacto de vapor para alimentar equipos de planchado y acabado.",
    benefits: [
      "Corte automático por falta de agua.",
      "Protección contra funcionamiento en seco.",
      "Sistema de protección en tres niveles.",
      "Control mediante sonda.",
      "Formato compacto.",
    ],
    imageAlt: "Generador de vapor BLCC LDR3-0.4R",
    ctaLabel: "Cotizar generador de vapor",
    relatedProductIds: ["ytt-1475", "hxgt-1", "jtj-1"],
    specTables: [
      {
        columns: ["LDR3-0.4R"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Potencia", values: ["3 kW"] },
          { label: "Presión máxima", values: ["0.3 MPa"] },
          { label: "Peso neto", values: ["45 kg"] },
        ],
      },
    ],
  },
  {
    id: "hxgt-1",
    slug: "mesa-planchado-deluxe-hxgt-1",
    category: "equipos-complementarios",
    name: "Mesa de planchado deluxe HXGT-1",
    summary:
      "Estación de acabado profesional con mesa, brazo y funciones de vapor y vacío para prendas de mayor complejidad.",
    benefits: [
      "Estación de acabado con mesa y brazo.",
      "Funciones de vapor y vacío.",
      "Orientada a prendas de mayor complejidad.",
    ],
    imageAlt: "Mesa de planchado deluxe BLCC HXGT-1",
    ctaLabel: "Cotizar mesa deluxe HXGT-1",
    relatedProductIds: ["ytt-1475", "ldr3-04r", "rxj-1"],
    specTables: [
      {
        columns: ["HXGT-1"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Presión de vacío indicada", values: ["≤ -150 Pa"] },
          { label: "Potencia", values: ["0.75 kW"] },
          { label: "Evaporación nominal indicada", values: ["4.3 kg"] },
          { label: "Presión de vapor", values: ["0.4 MPa"] },
          { label: "Peso neto", values: ["180 kg"] },
          { label: "Dimensiones", values: ["1700 × 500 × 1930 mm"] },
        ],
      },
    ],
  },
  {
    id: "ct",
    slug: "transportador-prendas-ct",
    category: "equipos-complementarios",
    name: "Transportador de prendas CT",
    summary:
      "Sistema transportador para organizar, almacenar y mover prendas dentro de una tintorería o centro de acabado.",
    benefits: [
      "Organización y almacenamiento de prendas.",
      "Transporte dentro de la tintorería o centro de acabado.",
      "Estructura de acero.",
      "Operación semiautomática.",
    ],
    imageAlt: "Transportador de prendas BLCC CT",
    ctaLabel: "Cotizar transportador de prendas",
    relatedProductIds: ["bzt-50", "rxj-1", "gxzq"],
    specTables: [
      {
        columns: ["CT"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Potencia de motor", values: ["0.85 kW"] },
          { label: "Estructura", values: ["Acero"] },
          { label: "Automatización", values: ["Semiautomática"] },
          { label: "Peso neto", values: ["180 kg"] },
        ],
      },
    ],
  },
  {
    id: "jtj-1",
    slug: "prensa-utilitaria-jtj-1",
    category: "equipos-complementarios",
    name: "Prensa utilitaria JTJ-1",
    summary:
      "Prensa profesional para acabado de prendas y piezas textiles mediante presión y vapor.",
    benefits: [
      "Acabado mediante presión y vapor.",
      "Uso profesional en prendas y piezas textiles.",
    ],
    imageAlt: "Prensa utilitaria BLCC JTJ-1",
    ctaLabel: "Cotizar prensa utilitaria JTJ-1",
    relatedProductIds: ["ytt-1475", "hxgt-1", "rxj-1"],
    specTables: [
      {
        columns: ["JTJ-1"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Potencia de motor", values: ["0.3 kW"] },
          { label: "Presión de vapor", values: ["0.4–0.6 MPa"] },
          { label: "Consumo de vapor indicado", values: ["18"] },
          { label: "Presión de aire", values: ["0.4–0.6 MPa"] },
          { label: "Consumo de aire", values: ["100 L/min"] },
          { label: "Dimensiones", values: ["1200 × 1280 × 1600 mm"] },
          { label: "Peso neto", values: ["260 kg"] },
        ],
      },
    ],
  },
  {
    id: "sws",
    slug: "mesa-desmanchado-sws",
    category: "equipos-complementarios",
    name: "Mesa de desmanchado SWS",
    summary:
      "Estación para tratamiento localizado de manchas antes o después del proceso de limpieza.",
    benefits: [
      "Tratamiento localizado de manchas.",
      "Uso antes o después del proceso de limpieza.",
    ],
    imageAlt: "Mesa de desmanchado BLCC SWS",
    ctaLabel: "Cotizar mesa de desmanchado SWS",
    relatedProductIds: ["swh", "gxzq", "rxj-1"],
    specTables: [
      {
        columns: ["SWS"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Potencia de motor", values: ["0.55 kW"] },
          { label: "Presión de vapor", values: ["0.15–0.5 MPa"] },
          { label: "Presión de aire indicada", values: ["0.15–0.7 MPa"] },
          { label: "Dimensiones", values: ["1000 × 450 × 1630 mm"] },
          { label: "Peso neto", values: ["76 kg"] },
        ],
      },
    ],
  },
  {
    id: "rxj-1",
    slug: "maniqui-acabado-rxj-1",
    category: "equipos-complementarios",
    name: "Maniquí de acabado RXJ-1",
    summary:
      "Equipo de acabado por aire y vapor para dar forma a prendas superiores después del lavado o limpieza en seco.",
    benefits: [
      "Acabado por aire y vapor.",
      "Da forma a prendas superiores.",
      "Uso después del lavado o limpieza en seco.",
    ],
    imageAlt: "Maniquí de acabado BLCC RXJ-1",
    ctaLabel: "Cotizar maniquí de acabado RXJ-1",
    relatedProductIds: ["hxgt-1", "jtj-1", "ct"],
    specTables: [
      {
        columns: ["RXJ-1"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Potencia de motor", values: ["0.55 kW"] },
          { label: "Presión de vapor", values: ["0.15–0.5 MPa"] },
          { label: "Dimensiones", values: ["1000 × 450 × 1630 mm"] },
          { label: "Peso neto", values: ["76 kg"] },
        ],
      },
    ],
  },
  {
    id: "bzd-1",
    slug: "lavadora-calzado-bzd-1",
    category: "equipos-complementarios",
    name: "Lavadora comercial de calzado BZD-1",
    summary: "Estación comercial orientada a limpieza especializada de calzado.",
    benefits: [
      "Limpieza especializada de calzado.",
      "Estación de uso comercial.",
    ],
    imageAlt: "Lavadora comercial de calzado BLCC BZD-1",
    ctaLabel: "Cotizar lavadora de calzado BZD-1",
    relatedProductIds: ["swq", "bzt-50"],
    specTables: [
      {
        columns: ["BZD-1"],
        rows: [
          { label: "Voltaje", values: ["220 V"] },
          { label: "Potencia de motor", values: ["0.28 kW"] },
          { label: "Frecuencia", values: ["50 Hz"] },
          { label: "Corriente nominal", values: ["3 A"] },
          { label: "Dimensiones", values: ["1200 × 550 × 1230 mm"] },
          { label: "Peso neto", values: ["68 kg"] },
        ],
      },
    ],
  },
  {
    id: "bzt-50",
    slug: "empacadora-prendas-bzt-50",
    category: "equipos-complementarios",
    name: "Empacadora de prendas BZT-50",
    summary:
      "Equipo para cubrir y empacar prendas terminadas, protegiéndolas durante almacenamiento, traslado y entrega.",
    benefits: [
      "Cubre y empaca prendas terminadas.",
      "Protección durante almacenamiento, traslado y entrega.",
    ],
    imageAlt: "Empacadora de prendas BLCC BZT-50",
    ctaLabel: "Cotizar empacadora BZT-50",
    relatedProductIds: ["ct", "rxj-1"],
    specTables: [
      {
        columns: ["BZT-50"],
        rows: [
          { label: "Potencia de motor", values: ["0.45 kW"] },
          { label: "Tamaño de película", values: ["500/600 mm"] },
          { label: "Voltaje", values: ["220 V"] },
          { label: "Dimensiones", values: ["690 × 600 × 1750 mm"] },
          { label: "Peso neto", values: ["53 kg"] },
        ],
      },
    ],
  },
];
